# -*- coding: utf-8 -*-
"""Assignment8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K0h5qDai7scA6QnXWk3MEMa3NNdCCmr5
"""

# Q1
from pylab import *
x=linspace(-2*pi,2*pi,513);x=x[:-1]
y=(sin(5*x))
Y=fftshift(fft(y))/512.0
w=linspace(-64,64,513);w=w[:-1]
figure()
subplot(2,1,1)
plot(w,abs(Y),lw=2)
xlim([-10,10])
ylabel(r"$|Y|$",size=16)
title(r"Spectrum of $\sin(5t)$")
grid(True)
subplot(2,1,2)
plot(w,angle(Y),'ro',lw=2)
ii=where(abs(Y)>1e-3)
plot(w[ii],angle(Y[ii]),'go',lw=2)
xlim([-10,10])
ylabel(r"Phase of $Y$",size=16)
xlabel(r"$k$",size=16)
grid(True)
savefig("fig1.png")
show()

from pylab import *
x=linspace(-4*pi,4*pi,513);x=x[:-1]
y=(1 + 0.1 * cos(x))*cos(10*x)
Y=fftshift(fft(y))/512.0
w=linspace(-64,64,513);w=w[:-1]
figure()
subplot(2,1,1)
plot(w,abs(Y),lw=2)
xlim([-15,15])
ylabel(r"$|Y|$",size=16)
title(r"Spectrum of $\sin^3(t)$")
grid(True)
subplot(2,1,2)
plot(w,angle(Y),'ro',lw=2)
ii=where(abs(Y)>1e-3)
plot(w[ii],angle(Y[ii]),'go',lw=2)
xlim([-15,15])
ylabel(r"Phase of $Y$",size=16)
xlabel(r"$k$",size=16)
grid(True)
savefig("fig2.png")
show()

# Q2
x=linspace(-4*pi,4*pi,513);x=x[:-1]
y=(sin(x))**3
Y=fftshift(fft(y))/512.0
w=linspace(-64,64,513);w=w[:-1]
figure()
subplot(2,1,1)
plot(w,abs(Y),lw=2)
xlim([-10,10])
ylabel(r"$|Y|$",size=16)
title(r"Spectrum of $\sin^3(t)$")
grid(True)
subplot(2,1,2)
plot(w,angle(Y),'ro',lw=2)
ii=where(abs(Y)>1e-3)
plot(w[ii],angle(Y[ii]),'go',lw=2)
xlim([-10,10])
ylabel(r"Phase of $Y$",size=16)
xlabel(r"$k$",size=16)
grid(True)

show()

x=linspace(-4*pi,4*pi,513);x=x[:-1]
y=(cos(x))**3
Y=fftshift(fft(y))/512.0
w=linspace(-64,64,513);w=w[:-1]
figure()
subplot(2,1,1)
plot(w,abs(Y),lw=2)
xlim([-10,10])
ylabel(r"$|Y|$",size=16)
title(r"Spectrum of $\cos^3(t)$")
grid(True)
subplot(2,1,2)
plot(w,angle(Y),'ro',lw=2)
ii=where(abs(Y)>1e-3)
plot(w[ii],angle(Y[ii]),'go',lw=2)
xlim([-10,10])
ylabel(r"Phase of $Y$",size=16)
xlabel(r"$k$",size=16)
grid(True)
savefig("fig4.png")
show()

# Q3
x=linspace(-4*pi,4*pi,513);x=x[:-1]
y=cos(20*x+5*cos(x))
Y=fftshift(fft(y))/512.0
w=linspace(-64,64,513);w=w[:-1]
figure()
subplot(2,1,1)
plot(w,abs(Y),lw=2)
xlim([-40,40])
ylabel(r"$|Y|$",size=16)
title(r"Spectrum of $\cos(20t+5cos(t))$")
grid(True)
subplot(2,1,2)
plot(w,angle(Y),'ro',lw=2)
ii=where(abs(Y)>1e-3)
plot(w[ii],angle(Y[ii]),'go',lw=2)
xlim([-40,40])
ylabel(r"Phase of $Y$",size=16)
xlabel(r"$k$",size=16)
grid(True)
savefig("fig5.png")
show()

# Q4
x=linspace(-4*pi,4*pi,513);x=x[:-1]
y=exp(-x**2/2) 
Y=fftshift(abs(fft(y)))/512.0
w=linspace(-32,32,513);w=w[:-1]
Y = Y*sqrt(2*pi) / max(Y)
Y_ = exp(-w**2/2)*sqrt(2*pi)
print("max error is {}".format(abs(Y-Y_).max()))
figure()
subplot(2,1,1)
plot(w,abs(Y),lw=2)
xlim([-10,10])
ylabel(r"$|Y|$",size=16)
title(r"Spectrum of $\exp(-t^2/2)$")
grid(True)
subplot(2,1,2)
plot(w,angle(Y),'ro',lw=2)
ii=where(abs(Y)>1e-3)
plot(w[ii],angle(Y[ii]),'go',lw=2)
xlim([-10,10])
ylabel(r"Phase of $Y$",size=16)
xlabel(r"$k$",size=16)
grid(True)
savefig("fig6.png")
show()

x=linspace(-8*pi,8*pi,513);x=x[:-1]
y=exp(-x**2/2) 
Y=fftshift(abs(fft(y)))/512.0
w=linspace(-32,32,513);w=w[:-1]
Y = Y*sqrt(2*pi) / max(Y)
Y_ = exp(-w**2/2)*sqrt(2*pi)
print("max error is {}".format(abs(Y-Y_).max()))
figure()
subplot(2,1,1)
plot(w,abs(Y),lw=2)
xlim([-10,10])
ylabel(r"$|Y|$",size=16)
title(r"Spectrum of $\exp(-t^2/2)$")
grid(True)
subplot(2,1,2)
plot(w,angle(Y),'ro',lw=2)
ii=where(abs(Y)>1e-3)
plot(w[ii],angle(Y[ii]),'go',lw=2)
xlim([-10,10])
ylabel(r"Phase of $Y$",size=16)
xlabel(r"$k$",size=16)
grid(True)
savefig("fig7.png")
show()

x=linspace(-10*pi,10*pi,513);x=x[:-1]
y=exp(-x**2/2) 
Y=fftshift(abs(fft(y)))/512.0
w=linspace(-32,32,513);w=w[:-1]
Y = Y*sqrt(2*pi) / max(Y)
Y_ = exp(-w**2/2)*sqrt(2*pi)
print("max error is {}".format(abs(Y-Y_).max()))
figure()
subplot(2,1,1)
plot(w,abs(Y),lw=2)
xlim([-10,10])
ylabel(r"$|Y|$",size=16)
title(r"Spectrum of $\exp(-t^2/2)$")
grid(True)
subplot(2,1,2)
plot(w,angle(Y),'ro',lw=2)
ii=where(abs(Y)>1e-3)
plot(w[ii],angle(Y[ii]),'go',lw=2)
xlim([-10,10])
ylabel(r"Phase of $Y$",size=16)
xlabel(r"$k$",size=16)
grid(True)
savefig("fig8.png")
show()

x=linspace(-8*pi,8*pi,257);x=x[:-1]
y=exp(-x**2/2) 
Y=fftshift(abs(fft(y)))/256.0
w=linspace(-32,32,257);w=w[:-1]
Y = Y*sqrt(2*pi) / max(Y)
Y_ = exp(-w**2/2)*sqrt(2*pi)
print("max error is {}".format(abs(Y-Y_).max()))
figure()
subplot(2,1,1)
plot(w,abs(Y),lw=2)
xlim([-10,10])
ylabel(r"$|Y|$",size=16)
title(r"Spectrum of $\exp(-t^2/2)$")
grid(True)
subplot(2,1,2)
plot(w,angle(Y),'ro',lw=2)
ii=where(abs(Y)>1e-3)
plot(w[ii],angle(Y[ii]),'go',lw=2)
xlim([-10,10])
ylabel(r"Phase of $Y$",size=16)
xlabel(r"$k$",size=16)
grid(True)
savefig("fig9.png")
show()

x=linspace(-4*pi,4*pi,1025);x=x[:-1]
y=exp(-x**2/2) 
Y=fftshift(abs(fft(y)))/1024.0
w=linspace(-32,32,1025);w=w[:-1]
Y = Y*sqrt(2*pi) / max(Y)
Y_ = exp(-w**2/2)*sqrt(2*pi)
print("max error is {}".format(abs(Y-Y_).max()))
figure()
subplot(2,1,1)
plot(w,abs(Y),lw=2)
xlim([-10,10])
ylabel(r"$|Y|$",size=16)
title(r"Spectrum of $\exp(-t^2/2)$")
grid(True)
subplot(2,1,2)
plot(w,angle(Y),'ro',lw=2)
ii=where(abs(Y)>1e-3)
plot(w[ii],angle(Y[ii]),'go',lw=2)
xlim([-10,10])
ylabel(r"Phase of $Y$",size=16)
xlabel(r"$k$",size=16)
grid(True)
savefig("fig10.png")
show()