# -*- coding: utf-8 -*-
"""Assignment6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rVFXQg1HZhAMSTw6vqvnDUQJ4XuYfF1F
"""

import scipy.signal as sp
from pylab import *
Num = poly1d([1,0.5])
Den = polymul([1,1,2.5],[1,0,2.25])
X=sp.lti(Num, Den)
t,x=sp.impulse(X,None,linspace(0,50,501))
plot(t,x)
title("Time Response for input having 0.5 as decay factor")
ylabel("x(t)")
xlabel("t (sec)")
savefig('0.5decay.png')
show()

Num = poly1d([1,0.05])
Den = polymul([1,0.1,2.275],[1,0,2.25])
X0=sp.lti(Num, Den)
t,x0=sp.impulse(X0,None,linspace(0,50,501))
plot(t,x0)
title("Time Response for input having 0.05 as decay factor")
ylabel("x(t)")
xlabel("t (sec)")
savefig('0.05decay.png')
show()

H = sp.lti([1],[1,0,2.25])
t = linspace(0,50,501)
title("Time Response for input having 0.05 as decay factor and $\omega$ varies between 1.4 to 1.6")
for w in arange(1.4,1.65,0.05):
  u = cos(w*t)*exp(-0.05*t)
  t,x,svec = sp.lsim(H,u,t)
  subplot(t,x)
  ylabel("x(t)")
  xlabel("t (sec)")
  savefig('wvary{}.png'.format(w))
  show()

"""Explain what is happening.

"""

X = sp.lti([1,0,2],[1,0,3,0])
Y = sp.lti([2],[1,0,3,0])
t,x=sp.impulse(X,None,linspace(0,20,101))
t,y=sp.impulse(Y,None,linspace(0,20,101))
plot(t,x)
title("Coupled spring problem, x(t)")
ylabel("x(t)")
xlabel("t (sec)")
savefig('x_t.png')
show()
plot(t,y)
title("Coupled spring problem, y(t)")
ylabel("y(t)")
xlabel("t (sec)")
savefig('y_t.png')
show()

R = 100; L = 1e-6; C = 1e-6
H = sp.lti([1],[L*C,R*C,1])
w,S,phi = H.bode()
subplot(2,1,1)
ylabel("|H(s)|")
xlabel("$\omega$ (1/sec)")
semilogx(w,S)
subplot(2,1,2)
semilogx(w,phi)
ylabel("phi(s)")
xlabel("$\omega$ (1/sec)")
savefig('Bodeplot.png')
show()

t0 = linspace(0,30e-6,301)
t1=linspace(0,10e-3,100000)
Vi0=(cos(1e3*t0) - cos(1e6*t0))*np.heaviside(t0,0.5)
Vi1=(cos(1e3*t1) - cos(1e6*t1))*np.heaviside(t1,0.5)
t0,Vo0,svec=sp.lsim(H,Vi0,t0)
t1,Vo1,svec=sp.lsim(H,Vi1,t1)
plot(t0,Vo0)
ylabel("Vo(t)")
xlabel("t (sec)")
savefig('Vo_t1.png')
show()
plot(t1,Vo1)
ylabel("Vo(t)")
xlabel("t (sec)")
savefig('Vo_t2.png')
show()

"""How do you explain the output signal for 0 < t < 30µs? Can you explain the long
term response on the msec timescale?
"""